# -*- coding: utf-8 -*-
"""Assignment_9_CS_202051211.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D9oWn1Z0IZsSzM94cW8ULQViHFob2lWP
"""

import numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

"""1. Check which version of the game is better by computing average ”sum gamerounds”.
2. To check that the difference in average of ”sum gamerounds” is by chance or it is a real
difference, perform the permutation Resampling on the data and derive the probability. Make
the decision based on derived probability.
"""

df = pd.read_csv("cookie_cats.csv")
df

mu_a = df[df['version'] == 'gate_30'].sum_gamerounds.mean()
mu_b = df[df['version'] == 'gate_40'].sum_gamerounds.mean()

print("Mean sum of gamerounds gate_30 : ", mu_a)
print("Mean sum of gamerounds gate_40 : ", mu_b)
print("Difference Between average of sum of gamerounds : ", mu_a - mu_b)

ax = df.boxplot(by='version', column='sum_gamerounds')
ax.set_xlabel('')
ax.set_ylabel('Time (in seconds)')
plt.title('Sum of Gamegrounds')

import random

def permutatation_test_fun(x, nA, nB):
    n = nA + nB
    idx_B = set(random.sample(range(n), nB))
    idx_A = set(range(n)) - idx_B
    return x.loc[idx_A].mean() - x.loc[idx_B].mean()

nA= len(df[df['version'] == 'gate_30'])
nA

nB=len(df[df['version'] == 'gate_40'])
nB

permutation_difference = [permutatation_test_fun(df.sum_gamerounds, nA, nB) for _ in range(500)]

fig, ax = plt.subplots(figsize=(7, 5))
ax.hist(permutation_difference, bins=20, rwidth=1)

# original mean difference
ax.axvline(x= mu_a -mu_b, color='black', lw=2)

ax.set_xlabel('Session time difference (sec)')
ax.set_ylabel('Frequency')
plt.show()

numpy.mean(permutation_difference > mu_a - mu_b)

