# -*- coding: utf-8 -*-
"""Assignment10_CS_202051211.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f0DK_AsrPAqJsUuX2WPjxLNWej3776rG

# Assignment 10

## Glen Quadros 202051211
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""1. Perform t-test on cookie cats data and make conclusions from derived p-value."""

df_cc = pd.read_csv('/content/cookie_cats.csv')

df_cc.head()

from scipy.stats import ttest_ind

gate_30 = df_cc[df_cc['version'] == 'gate_30']['sum_gamerounds']
gate_40 = df_cc[df_cc['version'] == 'gate_40']['sum_gamerounds']

t_stat, p_val = ttest_ind(gate_30, gate_40, equal_var=False)

print('t-statistic:', t_stat)
print('p-value:', p_val)

"""2. Create contingency table from ”Specialism” and ”Batting” type of player from IPL Data.
Perform Chi square test on data in contingency table.
"""

df_ipl = pd.read_csv('/content/IPL_Auction_2022_FullList.csv')

df_ipl.head()

from scipy.stats import chi2_contingency

cont_table = pd.crosstab(df_ipl['Specialism'], df_ipl['Batting'])
print(cont_table)

chi2_stat, p_val, dof, expected = chi2_contingency(cont_table)

print('Chi-square statistic:', chi2_stat)
print('p-value:', p_val)
print('Degrees of freedom:', dof)

